#include "AIPS.h"

/*
 * Will create a CRC check table from the polynomial passed in as a
 * second argument in the table pointer in the first. (The pointer
 * must point to an array at least 256 in size.)
 * @param unsigned int *table An unsigned integer array of at least
 * 256 that will be populated with CRC values.
 * @param unsigned int polynomial A number to use to generate the
 * table.
 */
void crcTable(unsigned int *table, unsigned int polynomial){
  unsigned int current;
  int i, ii;

  for(i = 0; i < 256; i++){
    current = i;
    for(ii = 8; ii > 0; ii--)
      if(current & 1)
	current = (current >> 1) ^ polynomial;
      else
	current >>= 1;

    table[i] = current;
  }
}

/*
 * Will generate a CRC value for a file up until the current read
 * position.
 * @param FILE *file The file to generate a CRC for... If the read
 * position of the file isn't at the beginning of the file, it will
 * read up to the point the pointer currently is at only, and generate
 * a CRC using only that.
 * unsigned int *crcTable A CRC table as generated by crcTable()
 * above. This will be used to create the CRC value; different table
 * means a diferent CRC result.
 * @returns unsigned int CRC check value; the result of the CRC.
 */
unsigned int crcFile(FILE *file, unsigned int *crcTable){
  unsigned int crc = 0xFFFFFFFF;
  unsigned char buffer;
  unsigned long i = 0L,
                lastPosition = ftell(file);

  if(lastPosition == 0){
    fseek(file, 0L, SEEK_END);
    lastPosition = ftell(file);
  }

  rewind(file);

  while(fread(&buffer, BYTE, 1, file) && lastPosition > i++)
    crc = (crc >> 8) ^ crcTable[buffer ^ ((crc) & 0x000000FF)];

  fseek(file, lastPosition, SEEK_SET);
  return crc ^ ~0U;
}
